---
title: "肠道菌群研究二十年·大数据"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

```{r}
library(ggplot2)
```


# 数据来源和分析方法

数据来源于两个文献数据库，分别是Web of Science（英文）和万方数据库（中文）。
主要采用的是文献计量学方法，包括R语言的软件包 `bibliometerix` 和其它一些[自编函数](./R)。
文章中给出了更多相关信息。

# WoS 来源数据分析结果

## 研究的增长


## 研究脉络


## 研究机构和研究团队


## 研究领域


## 发展趋势


# 万方来源数据分析结果

## 发文量

```{r}
library(dplyr)
library(readr)
library(export)
yearly_output <- read_tsv("data/wanfang-yearly-output.tsv", comment = "#")


ggplot(yearly_output,aes(year,nRecord)) +
  geom_col() +
  labs(x="",y="",title = "万方数据库中肠道菌群相关研究论文的增长情况")
graph2ppt(append = TRUE)
```

```{r}
hbarplot <- function(d){
  require(forcats)
  if (ncol(d) != 2) stop("data must have only two columns.")
  colnames(d) <- c("name","value")
  v <- max(d$value)/2
ggplot(d, aes(fct_rev(as_factor(name)), value)) + geom_col() + 
    labs(x = "", y = "No. of record") + 
    geom_text(aes(label = name, y = value - 1), size = 3, 
        vjust = 0.3, hjust = 1, data = function(d) d[d$value > v, ], color = "white", fontface = "bold") + 
    geom_text(aes(label = name, y = value + 1), size = 3, 
        vjust = 0.5, hjust = 0, data = function(d) d[d$value <= v, ]) + 
  coord_flip() + 
  theme_light() + 
  theme(axis.text.y = element_blank())
}

```

## 机构

```{r fig.width=5}
top_university <- read_tsv("data/wanfang-top-university.tsv",comment = "#")
p_top_univ <- hbarplot(top_university) +
  labs(title = "发表论文最多的10家研究机构")
```

```{r fig.asp=0.5}
top_journal <- read_tsv("data/wanfang-top-journal.tsv",comment = "#")
p_top_journal <- hbarplot(top_journal) +
  labs(title = "发文量最大的10家期刊")

cowplot::plot_grid(p_top_univ,p_top_journal,ncol = 2,labels = "AUTO")
graph2ppt(append = TRUE)

```

```{r fig.asp=1}
region_expansion <- read_tsv("data/wanfang-region-expansion.tsv",comment = "#") %>%
  tidyr::fill(region,.direction="down") %>%
  mutate(region=stringr::str_wrap(region,width = 12))
library(ccgraph)
node <- gather_graph_node(region_expansion,index = c("region","keyword"),root = "gut microbiome")
edge <- gather_graph_edge(region_expansion,index = c("region","keyword"),root = "gut microbiome")
library(tidygraph)
g <- tbl_graph(node,edge)
library(ggraph)
ggraph(g,layout = "dendrogram",circular=TRUE) +
  geom_edge_diagonal(aes(color=node1.node.branch),alpha=1/3) + 
  geom_node_point(aes(size=node.size,color=node.branch),alpha=1/3,data = function(d) filter(d, node.level != "gut microbiome")) + 
  coord_fixed() +
  theme(legend.position = "none") +
  scale_size(range = c(3,40)) +
  geom_node_text(
    aes(
      x = 1.18 * x,
      y = 1.18 * y,
      label = node.short_name,
      angle = -((-node_angle(x, y) + 90) %% 180) + 90,
      filter = leaf,
      color = node.branch
    ), 
    size = 3, hjust = 'outward'
    ) +
  geom_node_text(
    aes(label=node.short_name,
        color = node.branch),
    fontface="bold",
    size=3,
    family="sans",
    data = function(d) filter(d,node.level=="region"),
  ) +
  xlim(c(-2,2)) +
  ylim(c(-2,2))
graph2ppt(append = TRUE)

```


